spring.application.name=MyExpenseTracker

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseDB
spring.datasource.username=root
spring.datasource.password=Prat@1234

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Delays database initialization until the Hibernate entities are created.
spring.jpa.defer-datasource-initialization=true

#Forces SQL script initialization to run regardless of the database type.
spring.sql.init.mode=always

##Specifies the location of the SQL script used to populate the database with data.


logging.level.org.springframework.jdbc.datasource.init=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.cache=TRACE
